name: CI

on: [push]

jobs:
  translations:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: |
        sudo apt-get install -y libclang-dev
        sudo apt-get install -y llvm
        sudo apt-get install -y pkg-config
        sudo apt-get install -y libgtk2.0-dev
        sudo apt-get install -y libfreetype6
        sudo apt-get install -y libfreetype-dev
        sudo apt-get install -y libfreetype6-dev


    - uses: Dovyski/setup-opencv-action@v1.1
      with:
        opencv-version: 4.9.0
        ENABLE_PRECOMPILED_HEADERS: OFF
        GENERATE_PKGCONFIG: ON

    - uses: actions-rs/toolchain@v1
      with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

       
    - run: cargo build --release      
